2024/11/28 01:57:19 [error] 30#30: *3 open() "/usr/share/nginx/html/apple-touch-icon-precomposed.png" failed (2: No such file or directory), client: 192.168.65.1, server: localhost, request: "GET /apple-touch-icon-precomposed.png HTTP/1.1", host: "localhost:8080"
2024/11/28 01:57:19 [error] 30#30: *3 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: 192.168.65.1, server: localhost, request: "GET /apple-touch-icon-precomposed.png HTTP/1.1", host: "localhost:8080"
2024/11/28 01:57:19 [error] 30#30: *3 open() "/usr/share/nginx/html/apple-touch-icon.png" failed (2: No such file or directory), client: 192.168.65.1, server: localhost, request: "GET /apple-touch-icon.png HTTP/1.1", host: "localhost:8080"
2024/11/28 01:57:19 [error] 30#30: *3 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: 192.168.65.1, server: localhost, request: "GET /apple-touch-icon.png HTTP/1.1", host: "localhost:8080"
2024/11/28 01:57:19 [error] 30#30: *2 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.65.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2024/11/28 01:57:19 [error] 30#30: *2 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: 192.168.65.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2024/11/28 06:57:41 [error] 30#30: *2 open() "/usr/share/nginx/html/nginx_status" failed (2: No such file or directory), client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 06:57:41 [error] 30#30: *2 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 06:59:48 [notice] 37#37: signal process started
2024/11/28 07:01:47 [error] 38#38: *3 open() "/usr/share/nginx/html/nginx_status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost"
2024/11/28 07:01:47 [error] 38#38: *3 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost"
2024/11/28 07:02:01 [error] 38#38: *4 open() "/usr/share/nginx/html/nginx_status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "127.0.0.1"
2024/11/28 07:02:01 [error] 38#38: *4 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "127.0.0.1"
2024/11/28 07:03:38 [error] 38#38: *5 open() "/usr/share/nginx/html/nginx_status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "127.0.0.1"
2024/11/28 07:03:38 [error] 38#38: *5 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "127.0.0.1"
2024/11/28 07:06:32 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:33 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:34 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:34 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:34 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:34 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:34 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:34 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:34 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:35 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:35 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2024/11/28 07:06:35 [error] 30#30: *2 access forbidden by rule, client: 192.168.65.1, server: localhost, request: "GET /nginx_status HTTP/1.1", host: "localhost:8080"
2025/01/01 14:29:55 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:29:56 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:29:56 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:29:57 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:29:57 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:29:59 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:30:03 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:30:09 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:30:22 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:30:48 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:31:39 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:32:40 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 14:49:05 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:09:06 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:25:31 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:32:15 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:33:15 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:34:16 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:35:16 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:36:16 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:37:16 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:38:16 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:39:17 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:06 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:06 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:06 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:07 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:08 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:10 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:13 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:19 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:32 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:40:58 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:41:50 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:42:50 [emerg] 1#1: host not found in upstream "chatservice:5000" in /etc/nginx/nginx.conf:21
2025/01/01 15:51:24 [error] 29#29: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:55:00 [error] 29#29: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:55:01 [error] 29#29: *34 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:55:02 [error] 29#29: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:55:02 [error] 29#29: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:55:02 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:55:02 [error] 29#29: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:55:02 [error] 29#29: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:55:02 [error] 29#29: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 15:57:39 [error] 29#29: *55 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 16:06:13 [error] 29#29: *74 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 16:06:36 [error] 29#29: *77 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/chat/send", host: "localhost:8081"
2025/01/01 16:12:21 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/01 16:12:22 [error] 30#30: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/01 16:12:22 [error] 30#30: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/01 16:12:22 [error] 30#30: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/01 16:12:23 [error] 30#30: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/01 16:12:23 [error] 30#30: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/01 16:12:23 [error] 30#30: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/01 16:12:23 [error] 30#30: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/01 16:22:38 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.18.0.5:5000/api/Chat/send", host: "localhost:8081"
2025/01/02 16:09:18 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:09:19 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:09:19 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:09:20 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:09:21 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:09:23 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:09:26 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:09:33 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:09:46 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:10:13 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:11:06 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:47
2025/01/02 16:12:06 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:42
2025/01/02 16:13:07 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:42
2025/01/02 16:14:07 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:42
2025/01/02 16:15:07 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/nginx.conf:42
2025/01/02 16:56:06 [error] 30#30: *79 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/02 16:57:22 [error] 30#30: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/api/Chat/send", host: "localhost:8081"
2025/01/02 16:57:23 [error] 30#30: *84 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/api/Chat/send", host: "localhost:8081"
2025/01/02 16:57:23 [error] 30#30: *88 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/api/Chat/send", host: "localhost:8081"
2025/01/02 16:59:38 [error] 30#30: *91 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:20:28 [error] 30#30: *96 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:14 [error] 30#30: *99 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:15 [error] 30#30: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:16 [error] 30#30: *105 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:16 [error] 30#30: *107 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:16 [error] 30#30: *111 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:16 [error] 30#30: *113 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:17 [error] 30#30: *116 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:17 [error] 30#30: *120 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:17 [error] 30#30: *123 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:17 [error] 30#30: *125 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:17 [error] 30#30: *129 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:17 [error] 30#30: *132 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:17 [error] 30#30: *134 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:18 [error] 30#30: *138 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:18 [error] 30#30: *140 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:18 [error] 30#30: *144 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:18 [error] 30#30: *147 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:18 [error] 30#30: *149 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:18 [error] 30#30: *153 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:19 [error] 30#30: *155 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:24:19 [error] 30#30: *159 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.19.0.4:5000/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:21 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:22 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:22 [error] 30#30: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:22 [error] 30#30: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:22 [error] 30#30: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:23 [error] 30#30: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:23 [error] 30#30: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:23 [error] 30#30: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:23 [error] 30#30: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:23 [error] 30#30: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:23 [error] 30#30: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:23 [error] 30#30: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:24 [error] 30#30: *38 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:24 [error] 30#30: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:24 [error] 30#30: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:27:37 [error] 30#30: *56 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:05 [error] 30#30: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:06 [error] 30#30: *62 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:06 [error] 30#30: *64 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:06 [error] 30#30: *68 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:06 [error] 30#30: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:07 [error] 30#30: *74 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:07 [error] 30#30: *77 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:07 [error] 30#30: *79 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:07 [error] 30#30: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:07 [error] 30#30: *85 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:07 [error] 30#30: *89 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:28:32 [error] 30#30: *91 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "GET /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:38:41 [notice] 48#48: signal process started
2025/01/03 04:52:53 [error] 49#49: *94 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
2025/01/03 04:52:54 [error] 49#49: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: localhost, request: "POST /api/Chat/send HTTP/1.1", upstream: "http://172.20.0.5:5002/api/Chat/send", host: "localhost:8081"
